[project]
name = "dbt-data-quality"
version = "0.1.0"
description = "Data quality generic data tests for dbt"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.9.3",
    "dbt-duckdb>=1.9.2",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.11",
]
