name: CI

on: push

env:
  DBT_PROFILES_DIR: ./integration_tests
  DBT_PROJECT_DIR: ./integration_tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-duckdb

      - name: Change directory
        run: cd integration_tests

      - name: Install dbt dependencies
        run: dbt deps

      - name: Seed database
        run: dbt seed

      - name: Run tests
        run: dbt test
